//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloworld.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("helloworld.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will occur on {1} in {2}.
        ///.
        /// </summary>
        internal static string celebrate {
            get {
                return ResourceManager.GetString("celebrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Cinco de Mayo&quot;.
        /// </summary>
        internal static string holiday {
            get {
                return ResourceManager.GetString("holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain resources using the default UI culture (en-US)..
        /// </summary>
        internal static string langdefault {
            get {
                return ResourceManager.GetString("langdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain resources using the es-MX culture..
        /// </summary>
        internal static string langesMX {
            get {
                return ResourceManager.GetString("langesMX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtain resources using the fr-CA culture..
        /// </summary>
        internal static string langfrCA {
            get {
                return ResourceManager.GetString("langfrCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2021.
        /// </summary>
        internal static string year {
            get {
                return ResourceManager.GetString("year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this string is only in the default resources.
        /// </summary>
        internal static string ztest {
            get {
                return ResourceManager.GetString("ztest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .NET 5.0 world! No more core..
        /// </summary>
        internal static string zznet50 {
            get {
                return ResourceManager.GetString("zznet50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello .NET Core 3.1 world! Change is coming!.
        /// </summary>
        internal static string zznetcore {
            get {
                return ResourceManager.GetString("zznetcore", resourceCulture);
            }
        }
    }
}
